### ISSUE TITLE
queryServices() returns only services in the RUNNING state

### ISSUE THREAD

**Issue by adityamedhe** [tbenbrahim/windows-service-manager#1]
The documentation on NPM says that `queryServices()` returns all the services _installed_ on the system. However on running the method, I can see only the services in the RUNNING state being returned in the callback.

My code, for reference:
I am calling the method every second, and storing the retrieved information in `infoStore`, which is then sent as a HTTP response to every client.

```
var infoStore = {};

setInterval(serviceManager.queryServices, 1000, function(err, services) {
    console.log('HEART_BEAT');
    infoStore = services;
});

```

**Comment by adityamedhe** [comment]
I have created a pull request - #2 to solve this issue. Please let me know your thoughts.

**Comment by tbenbrahim** [comment]
Thank you very much  for the PR, it is merged now.
